# Generated by Django 5.2.10 on 2026-01-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "yearly_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "sham_cash_account",
                    models.CharField(default="Main Account", max_length=255),
                ),
                (
                    "sham_cash_number",
                    models.CharField(default="0900000000", max_length=255),
                ),
            ],
        ),
    ]
